version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"  # Expose port 5000 for Flask app
    volumes:
      - ./swagger:/app/swagger  # Mount the swagger folder with swagger.json
    environment:
      - SWAGGER_JSON_URL=/app/swagger/swagger.json  # Use the local swagger.json inside the container
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
