version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
    volumes:
      - ./swagger:/swagger
    depends_on:
      - flask-api  # Ensure Swagger UI waits for the Flask API service

  flask-api:
    build:
      context: ./api  # Build the Flask API from the Dockerfile in ./api
    container_name: flask-api
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
