version: '3.8'

services:
  api:
    build: ./api  # Path to your Flask app
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    volumes:
      - ./swagger:/app/swagger  # Mount the swagger directory for swagger.json
    environment:
      - SWAGGER_JSON_URL=/swagger/swagger.json  # Optional: Can be removed since it's handled locally
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
