version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
    volumes:
      - ./swagger:/swagger
